import { cookies } from 'next/headers'
import { randomBytes } from 'node:crypto'
import { ZodError } from 'zod'
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export async function owner(){const jar=await cookies();let key=jar.get('launchready_session')?.value;if(!key||!/^\w{64}$/.test(key)){key=randomBytes(32).toString('hex');jar.set('launchready_session',key,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*90})}return key}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');const expected=process.env.APP_ORIGIN||new URL(request.url).origin;if(origin&&origin!==expected)throw new HttpError(403,'Cross-origin request rejected.');if(request.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Cross-site request rejected.')}
export async function jsonBody(request:Request,maxBytes=10000){sameOrigin(request);if(!request.headers.get('content-type')?.includes('application/json'))throw new HttpError(415,'Send application/json.');const reader=request.body?.getReader();if(!reader)return {};let size=0;const parts:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>maxBytes){await reader.cancel();throw new HttpError(413,'Request too large.')}parts.push(value)}try{return JSON.parse(Buffer.concat(parts).toString('utf8'))}catch{throw new HttpError(400,'Invalid JSON.')}}
export function failure(e:unknown){if(e instanceof ZodError)return Response.json({error:'Input validation failed.',issues:e.issues.map(x=>`${x.path.join('.')}: ${x.message}`).slice(0,30)},{status:422});const status=e instanceof HttpError?e.status:typeof (e as {status?:unknown})?.status==='number'?(e as {status:number}).status:500;const message=e instanceof Error?e.message:'Request failed.';if(status===500)console.error('LaunchReady request failed:',message);return Response.json({error:status===500?'Backend unavailable. Check server configuration and try again.':message},{status,headers:{'Cache-Control':'no-store'}})}
export function ok(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
