import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { mkdtemp,rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join,resolve } from 'node:path'
import ExcelJS from 'exceljs'
import { makePdf } from './file-fixtures.mjs'
import { buildMissionPackage, makeCheck } from '../lib/intake.ts'
const dir=await mkdtemp(join(tmpdir(),'launchready-test-'));const origin='http://127.0.0.1:3105';let output=''
const server=spawn(process.execPath,['--import',resolve('tests/mock-gemini.mjs'),'node_modules/next/dist/bin/next','start','--port','3105','--hostname','127.0.0.1'],{env:{...process.env,GROQ_API_KEY:'integration-groq-only',GROQ_MODEL:'openai/gpt-oss-120b',GEMINI_API_KEY:'integration-gemini-only',TURSO_DATABASE_URL:`file:${dir}/app.db`,TURSO_AUTH_TOKEN:'',NEXT_TELEMETRY_DISABLED:'1'},stdio:['ignore','pipe','pipe']})
server.stdout.on('data',b=>{output+=b});server.stderr.on('data',b=>{output+=b});let cookie=''
async function request(path,init={},session=cookie){const headers=new Headers(init.headers);if(session)headers.set('Cookie',session);const response=await fetch(origin+path,{...init,headers});if(!cookie&&response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];return response}
const json=(body,extra={})=>({method:'POST',headers:{'Content-Type':'application/json',...extra},body:JSON.stringify(body)})
async function data(path,init){const r=await request(path,init);const body=await r.json();assert.ok(r.ok,`${path}: ${r.status} ${JSON.stringify(body)}`);return body}
async function run(packageId){let r=await data('/api/reviews',json({packageId}));for(let i=0;i<10&&r.status!=='COMPLETE';i++){const delay=r.aiRetry?Date.parse(r.aiRetry.nextAttemptAt)-Date.now():0;if(delay>0)await new Promise(resolve=>setTimeout(resolve,delay));r=await data(`/api/reviews/${r.id}/advance`,json({}))}assert.equal(r.status,'COMPLETE');return r}
try{
 let ready=false;for(let i=0;i<100;i++){if(server.exitCode!==null)throw new Error(output);try{const r=await fetch(origin+'/api/health');if(r.ok){ready=true;break}}catch{}await new Promise(r=>setTimeout(r,100))}if(!ready)throw new Error('Server did not start: '+output)
 const health=await data('/api/health');assert.equal(health.provider,'groq');assert.equal(health.model,'openai/gpt-oss-120b');assert.equal(health.embeddings,'configured');await data('/api/packages');assert.ok(cookie)
 // Exercise the real production PDF worker and spreadsheet parser, then run a confirmed form package.
 const intakeForm=new FormData();intakeForm.append('files',new File(['Time (s),Battery (V)\n0,12\n1,16\n2,11'], 'flight.csv'));intakeForm.append('files',new File([makePdf(['Battery voltage inspection completed.', 'Review signed by team engineer.'])], 'inspection.pdf'))
 const preview=await data('/api/intake',{method:'POST',body:intakeForm});assert.equal(preview.tables[0].rows.length,3);assert.equal(preview.documents[0].pages.length,2);assert.match(preview.documents[0].content,/## Page 2/)
 const prepared=buildMissionPackage({name:'CSV and PDF flight test',configuration:'v1',condition:'flight-test',startedAt:'2026-10-06T12:00:00Z',simulated:false,dataKind:'MEASURED',tableId:'TABLE-1',timeColumn:'Time (s)',timeFormat:'SECONDS',confirmed:true,checks:[{...makeCheck(),title:'Battery voltage',column:'Battery (V)',unit:'V',upper:'14',evidenceIds:[preview.documents[0].id]}]},preview)
 const preparedId=await data('/api/packages',json(prepared));const preparedReview=await run(preparedId.id);assert.equal(preparedReview.findings[0].current,16);assert.equal(preparedReview.findings[0].evaluation,'REVIEW_REQUIRED');assert.ok(preparedReview.chunks.some(c=>c.title==='inspection.pdf'&&c.section==='Page 2'));assert.match((await (await request(`/api/reviews/${preparedReview.id}/export`)).text()),/Reviewer-confirmed criteria/)
 const workbook=new ExcelJS.Workbook();workbook.addWorksheet('Flight').addRows([['Time (s)','Altitude (m)'],[0,12],[1,24]]);const excelForm=new FormData();excelForm.append('files',new File([await workbook.xlsx.writeBuffer()],'flight.xlsx'));const excel=await data('/api/intake',{method:'POST',body:excelForm});assert.deepEqual(excel.tables[0].rows,[['0','12'],['1','24']])
 const scanForm=new FormData();scanForm.append('files',new File([makePdf([''])],'scan.pdf'));const scan=await request('/api/intake',{method:'POST',body:scanForm});assert.equal(scan.status,422);assert.match((await scan.json()).error,/OCR/)
 assert.equal((await request('/api/intake',{method:'POST',body:intakeForm,headers:{origin:'https://untrusted.example'}})).status,403)
 const loaded=await data('/api/packages',json({}, {'x-launchready-demo':'1'}));const review=await run(loaded.id)
 assert.equal(review.findings.length,26);assert.equal(review.retrievalMode,'vector');assert.ok(review.events.filter(e=>e.stage.endsWith('AGENT')).every(e=>e.mode==='groq'))
 const battery=review.findings.find(f=>f.id==='BATTERY-THERMAL');assert.equal(battery.current,47);assert.equal(battery.evaluation,'REVIEW_REQUIRED');assert.ok(review.chunks.every(c=>!('vector' in c)))
 const denied=await request(`/api/reviews/${review.id}`,{},'launchready_session='+'a'.repeat(64));assert.equal(denied.status,404)
 const originDenied=await request('/api/reviews',json({packageId:loaded.id},{Origin:'https://untrusted.example'}));assert.equal(originDenied.status,403)
 const badNote=await request(`/api/reviews/${review.id}/notes`,json({findingId:battery.id,state:'DISMISSED_WITH_NOTE',note:''}));assert.equal(badNote.status,422)
 await data(`/api/reviews/${review.id}/notes`,json({findingId:battery.id,state:'NEEDS_ACTION',note:'Repeat thermal test.'}));const after=await data(`/api/reviews/${review.id}`);assert.equal(after.notes[battery.id].note,'Repeat thermal test.');assert.equal(after.findings[0].evaluation,'REVIEW_REQUIRED')
 const chat=await data('/api/chat',json({reviewId:review.id,question:'Why is battery temperature flagged?',findingId:battery.id}));assert.match(chat.mode,/Groq/);assert.ok(chat.citations.includes(battery.id));assert.ok(chat.chunkIds.every(id=>review.chunks.some(c=>c.id===id)))
 await data('/api/chat',json({reviewId:review.id,question:'What was my previous question?',findingId:battery.id}));const history=await data(`/api/chat?reviewId=${review.id}`);assert.equal(history.length,4)
 const md=await (await request(`/api/reviews/${review.id}/export`)).text();assert.ok(md.includes('Groq summary'));assert.ok(md.includes('Repeat thermal test.'));assert.ok(md.includes('does not approve or certify launches'));for(const f of review.findings)assert.ok(md.includes(f.id))
 const sample=await data('/api/sample');sample.mission.name='Uploaded scenario';sample.mission.id='CUSTOM-1';sample.baseline=null;for(const o of sample.observations.filter(o=>o.item_id===battery.id))o.value=20
 const form=new FormData();form.set('package',new File([JSON.stringify(sample)],'mission.json',{type:'application/json'}));const uploaded=await data('/api/packages',{method:'POST',body:form});const custom=await run(uploaded.id);assert.equal(custom.mission.name,'Uploaded scenario');assert.equal(custom.findings[0].current,20);assert.equal(custom.findings[0].status,'NOT_COMPARABLE');assert.equal(custom.findings[0].evaluation,'CHECK_PASSED')
 const invalid=structuredClone(sample);invalid.observations[0].value='bad';assert.equal((await request('/api/packages',json(invalid))).status,422)
 const csv='id,item_id,test_id,timestamp,value,unit,configuration_version,test_condition,valid\nONLY-1,BATTERY-THERMAL,TEST-1,2026-10-02T14:30:00Z,47,°C,demo-v1,bench-A,true\n';const csvForm=new FormData();csvForm.set('package',new File([JSON.stringify(sample)],'mission.json'));csvForm.set('observations',new File([csv],'observations.csv'));const csvP=await data('/api/packages',{method:'POST',body:csvForm});assert.equal(csvP.observations,1)
 // Inject a malicious API result through a test-only trigger; model JSON references must be checked.
 const malicious=await data('/api/chat',json({reviewId:review.id,question:'TEST_UNKNOWN_CITATION',findingId:battery.id}));assert.equal(malicious.mode,'Rule-based fallback')
 // A short report-only 429 must preserve preceding stages and survive a reload/early advance.
 const retryPackage=structuredClone(sample);retryPackage.requirements[0].title='TEST_REPORT_RETRY';const retryP=await data('/api/packages',json(retryPackage));let pending=await data('/api/reviews',json({packageId:retryP.id}));while(pending.stage!=='REPORT_AGENT')pending=await data(`/api/reviews/${pending.id}/advance`,json({}));const beforeRetry=pending;pending=await data(`/api/reviews/${pending.id}/advance`,json({}));assert.equal(pending.status,'RUNNING');assert.equal(pending.stage,'REPORT_AGENT');assert.equal(pending.aiRetry.attempt,1);assert.equal(pending.aiRetry.failure.httpStatus,429);assert.ok(!pending.events.some(e=>e.stage==='REPORT_AGENT'));assert.deepEqual(pending.findings,beforeRetry.findings);assert.deepEqual(pending.agentEvidence,beforeRetry.agentEvidence);assert.deepEqual(pending.narrative.relationships,beforeRetry.narrative.relationships);assert.equal(pending.narrative.summaryFailure,undefined)
 const reloaded=await data(`/api/reviews/${pending.id}`);assert.deepEqual(reloaded.aiRetry,pending.aiRetry);const early=await data(`/api/reviews/${pending.id}/advance`,json({}));assert.equal(early.stage,'REPORT_AGENT');assert.deepEqual(early.aiRetry,pending.aiRetry);await new Promise(resolve=>setTimeout(resolve,Math.max(0,Date.parse(pending.aiRetry.nextAttemptAt)-Date.now())+20));const recovered=await data(`/api/reviews/${pending.id}/advance`,json({}));assert.equal(recovered.status,'COMPLETE');assert.equal(recovered.narrative.summaryMode,'groq');assert.equal(recovered.aiRetry,undefined);assert.equal(recovered.narrative.summaryFailure,undefined);assert.equal(recovered.events.filter(e=>e.stage==='REPORT_AGENT').length,1);assert.match(recovered.events.at(-1).detail,/Recovered/)
 // One repeat failure or a daily-sized wait still completes with the explicit code fallback.
 for(const marker of ['TEST_REPORT_ALWAYS_429','TEST_REPORT_LONG_429']){const quotaPackage=structuredClone(sample);quotaPackage.requirements[0].title=marker;const quotaP=await data('/api/packages',json(quotaPackage));const quota=await run(quotaP.id);assert.equal(quota.narrative.summaryMode,'code');assert.equal(quota.narrative.summaryFailure.code,'QUOTA');assert.equal(quota.aiRetry,undefined);assert.ok(quota.events.filter(e=>['EVIDENCE_AGENT','ANALYSIS_AGENT'].includes(e.stage)).every(e=>e.mode==='groq'));assert.equal(quota.events.filter(e=>e.stage==='REPORT_AGENT').length,1)}
 const fallbackPackage=structuredClone(sample);fallbackPackage.requirements[0].title='FAIL-AI';const failedP=await data('/api/packages',json(fallbackPackage));const fallback=await run(failedP.id);assert.equal(fallback.status,'COMPLETE');assert.ok(fallback.events.filter(e=>e.stage.endsWith('AGENT')).every(e=>e.mode==='fallback'));assert.equal(fallback.findings[0].current,20);assert.ok(fallback.narrative.summary.includes('configured checks'));assert.equal(fallback.narrative.summaryMode,'code');assert.equal(fallback.narrative.summaryFailure.code,'QUOTA');assert.ok(fallback.narrative.summaryFailure.reason.includes('429'));const fallbackExport=await (await request(`/api/reviews/${fallback.id}/export`)).text();assert.ok(fallbackExport.includes('Code-generated fallback'));assert.ok(fallbackExport.includes('QUOTA'));
 for(const [status,code] of [[401,'AUTHENTICATION'],[429,'QUOTA'],[504,'TIMEOUT']]){const reply=await data('/api/chat',json({reviewId:review.id,question:`TEST_HTTP_${status}`}));assert.equal(reply.mode,'Rule-based fallback');assert.equal(reply.failure.code,code);assert.ok(reply.answer.includes('Code-generated review summary'));const saved=await data(`/api/chat?reviewId=${review.id}`);assert.equal(saved.at(-1).failure.code,code)}
 const missing=await request('/api/chat',json({reviewId:review.id,question:'Hello',findingId:'NO-SUCH-FINDING'}));assert.equal(missing.status,404)
 console.log('Integration passed: CSV/XLSX/PDF intake, confirmed checks, peak detection, scan rejection, agents, scoped storage, notes, exports, chat, citation rejection, saved cooldown, retry recovery, and bounded quota fallback.')
}finally{server.kill('SIGTERM');await new Promise(r=>{if(server.exitCode!==null)r();else server.once('exit',r)});await rm(dir,{recursive:true,force:true})}
